/* C++ code produced by gperf version 3.0.3 */
/* Command-line: gperf --key-positions='*' -D -n -s 2 CSSPropertyNames.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "CSSPropertyNames.gperf"

/* This file is automatically generated from CSSPropertyNames.in by makeprop, do not edit */
#include "CSSPropertyNames.h"
#include "HashTools.h"
#include <string.h>

namespace WebCore {
enum
  {
    TOTAL_KEYWORDS = 318,
    MIN_WORD_LENGTH = 3,
    MAX_WORD_LENGTH = 43,
    MIN_HASH_VALUE = 40,
    MAX_HASH_VALUE = 4556
  };

/* maximum key range = 4517, duplicates = 0 */

class CSSPropertyNamesHash
{
private:
  static inline unsigned int propery_hash_function (const char *str, unsigned int len);
public:
  static const struct Property *findPropertyImpl (const char *str, unsigned int len);
};

inline unsigned int
CSSPropertyNamesHash::propery_hash_function (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557,    0, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557,    5,    0,   20,
        30,    0,  666,  465,  980,    5,    0,    0,    5,  180,
        90,    0,  300,   10,   15,   20,    5,  975,  805,    5,
         1,  126,   50, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557, 4557,
      4557, 4557, 4557, 4557, 4557, 4557
    };
  register int hval = 0;

  switch (len)
    {
      default:
        hval += asso_values[(unsigned char)str[42]];
      /*FALLTHROUGH*/
      case 42:
        hval += asso_values[(unsigned char)str[41]];
      /*FALLTHROUGH*/
      case 41:
        hval += asso_values[(unsigned char)str[40]];
      /*FALLTHROUGH*/
      case 40:
        hval += asso_values[(unsigned char)str[39]];
      /*FALLTHROUGH*/
      case 39:
        hval += asso_values[(unsigned char)str[38]];
      /*FALLTHROUGH*/
      case 38:
        hval += asso_values[(unsigned char)str[37]];
      /*FALLTHROUGH*/
      case 37:
        hval += asso_values[(unsigned char)str[36]];
      /*FALLTHROUGH*/
      case 36:
        hval += asso_values[(unsigned char)str[35]];
      /*FALLTHROUGH*/
      case 35:
        hval += asso_values[(unsigned char)str[34]];
      /*FALLTHROUGH*/
      case 34:
        hval += asso_values[(unsigned char)str[33]];
      /*FALLTHROUGH*/
      case 33:
        hval += asso_values[(unsigned char)str[32]];
      /*FALLTHROUGH*/
      case 32:
        hval += asso_values[(unsigned char)str[31]];
      /*FALLTHROUGH*/
      case 31:
        hval += asso_values[(unsigned char)str[30]];
      /*FALLTHROUGH*/
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      /*FALLTHROUGH*/
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      /*FALLTHROUGH*/
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      /*FALLTHROUGH*/
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      /*FALLTHROUGH*/
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static const struct Property property_wordlist[] =
  {
#line 22 "CSSPropertyNames.gperf"
    {"color", CSSPropertyColor},
#line 87 "CSSPropertyNames.gperf"
    {"clear", CSSPropertyClear},
#line 242 "CSSPropertyNames.gperf"
    {"-webkit-locale", CSSPropertyWebkitLocale},
#line 137 "CSSPropertyNames.gperf"
    {"src", CSSPropertySrc},
#line 51 "CSSPropertyNames.gperf"
    {"border", CSSPropertyBorder},
#line 167 "CSSPropertyNames.gperf"
    {"widows", CSSPropertyWidows},
#line 302 "CSSPropertyNames.gperf"
    {"-webkit-text-stroke", CSSPropertyWebkitTextStroke},
#line 169 "CSSPropertyNames.gperf"
    {"word-break", CSSPropertyWordBreak},
#line 136 "CSSPropertyNames.gperf"
    {"size", CSSPropertySize},
#line 134 "CSSPropertyNames.gperf"
    {"resize", CSSPropertyResize},
#line 59 "CSSPropertyNames.gperf"
    {"border-color", CSSPropertyBorderColor},
#line 303 "CSSPropertyNames.gperf"
    {"-webkit-text-stroke-color", CSSPropertyWebkitTextStrokeColor},
#line 204 "CSSPropertyNames.gperf"
    {"-webkit-border-start", CSSPropertyWebkitBorderStart},
#line 215 "CSSPropertyNames.gperf"
    {"-webkit-box-orient", CSSPropertyWebkitBoxOrient},
#line 240 "CSSPropertyNames.gperf"
    {"-webkit-line-break", CSSPropertyWebkitLineBreak},
#line 213 "CSSPropertyNames.gperf"
    {"-webkit-box-lines", CSSPropertyWebkitBoxLines},
#line 205 "CSSPropertyNames.gperf"
    {"-webkit-border-start-color", CSSPropertyWebkitBorderStartColor},
#line 23 "CSSPropertyNames.gperf"
    {"direction", CSSPropertyDirection},
#line 172 "CSSPropertyNames.gperf"
    {"z-index", CSSPropertyZIndex},
#line 141 "CSSPropertyNames.gperf"
    {"text-decoration", CSSPropertyTextDecoration},
#line 210 "CSSPropertyNames.gperf"
    {"-webkit-box-direction", CSSPropertyWebkitBoxDirection},
#line 83 "CSSPropertyNames.gperf"
    {"bottom", CSSPropertyBottom},
#line 99 "CSSPropertyNames.gperf"
    {"list-style", CSSPropertyListStyle},
#line 196 "CSSPropertyNames.gperf"
    {"-webkit-border-end", CSSPropertyWebkitBorderEnd},
#line 89 "CSSPropertyNames.gperf"
    {"content", CSSPropertyContent},
#line 75 "CSSPropertyNames.gperf"
    {"border-style", CSSPropertyBorderStyle},
#line 260 "CSSPropertyNames.gperf"
    {"-webkit-mask", CSSPropertyWebkitMask},
#line 219 "CSSPropertyNames.gperf"
    {"-webkit-color-correction", CSSPropertyWebkitColorCorrection},
#line 36 "CSSPropertyNames.gperf"
    {"zoom", CSSPropertyZoom},
#line 142 "CSSPropertyNames.gperf"
    {"text-indent", CSSPropertyTextIndent},
#line 197 "CSSPropertyNames.gperf"
    {"-webkit-border-end-color", CSSPropertyWebkitBorderEndColor},
#line 33 "CSSPropertyNames.gperf"
    {"-webkit-text-orientation", CSSPropertyWebkitTextOrientation},
#line 52 "CSSPropertyNames.gperf"
    {"border-bottom", CSSPropertyBorderBottom},
#line 311 "CSSPropertyNames.gperf"
    {"-webkit-transition", CSSPropertyWebkitTransition},
#line 206 "CSSPropertyNames.gperf"
    {"-webkit-border-start-style", CSSPropertyWebkitBorderStartStyle},
#line 53 "CSSPropertyNames.gperf"
    {"border-bottom-color", CSSPropertyBorderBottomColor},
#line 278 "CSSPropertyNames.gperf"
    {"-webkit-mask-size", CSSPropertyWebkitMaskSize},
#line 161 "CSSPropertyNames.gperf"
    {"top", CSSPropertyTop},
#line 294 "CSSPropertyNames.gperf"
    {"-webkit-text-combine", CSSPropertyWebkitTextCombine},
#line 138 "CSSPropertyNames.gperf"
    {"speak", CSSPropertySpeak},
#line 88 "CSSPropertyNames.gperf"
    {"clip", CSSPropertyClip},
#line 239 "CSSPropertyNames.gperf"
    {"-webkit-line-box-contain", CSSPropertyWebkitLineBoxContain},
#line 216 "CSSPropertyNames.gperf"
    {"-webkit-box-pack", CSSPropertyWebkitBoxPack},
#line 198 "CSSPropertyNames.gperf"
    {"-webkit-border-end-style", CSSPropertyWebkitBorderEndStyle},
#line 76 "CSSPropertyNames.gperf"
    {"border-top", CSSPropertyBorderTop},
#line 171 "CSSPropertyNames.gperf"
    {"word-wrap", CSSPropertyWordWrap},
#line 173 "CSSPropertyNames.gperf"
    {"-webkit-animation", CSSPropertyWebkitAnimation},
#line 77 "CSSPropertyNames.gperf"
    {"border-top-color", CSSPropertyBorderTopColor},
#line 56 "CSSPropertyNames.gperf"
    {"border-bottom-style", CSSPropertyBorderBottomStyle},
#line 58 "CSSPropertyNames.gperf"
    {"border-collapse", CSSPropertyBorderCollapse},
#line 312 "CSSPropertyNames.gperf"
    {"-webkit-transition-delay", CSSPropertyWebkitTransitionDelay},
#line 132 "CSSPropertyNames.gperf"
    {"position", CSSPropertyPosition},
#line 112 "CSSPropertyNames.gperf"
    {"opacity", CSSPropertyOpacity},
#line 332 "CSSPropertyNames.gperf"
    {"-webkit-opacity", CSSPropertyOpacity},
#line 86 "CSSPropertyNames.gperf"
    {"caption-side", CSSPropertyCaptionSide},
#line 24 "CSSPropertyNames.gperf"
    {"display", CSSPropertyDisplay},
#line 80 "CSSPropertyNames.gperf"
    {"border-top-style", CSSPropertyBorderTopStyle},
#line 275 "CSSPropertyNames.gperf"
    {"-webkit-mask-repeat", CSSPropertyWebkitMaskRepeat},
#line 276 "CSSPropertyNames.gperf"
    {"-webkit-mask-repeat-x", CSSPropertyWebkitMaskRepeatX},
#line 268 "CSSPropertyNames.gperf"
    {"-webkit-mask-clip", CSSPropertyWebkitMaskClip},
#line 174 "CSSPropertyNames.gperf"
    {"-webkit-animation-delay", CSSPropertyWebkitAnimationDelay},
#line 175 "CSSPropertyNames.gperf"
    {"-webkit-animation-direction", CSSPropertyWebkitAnimationDirection},
#line 140 "CSSPropertyNames.gperf"
    {"text-align", CSSPropertyTextAlign},
#line 209 "CSSPropertyNames.gperf"
    {"-webkit-box-align", CSSPropertyWebkitBoxAlign},
#line 101 "CSSPropertyNames.gperf"
    {"list-style-position", CSSPropertyListStylePosition},
#line 102 "CSSPropertyNames.gperf"
    {"list-style-type", CSSPropertyListStyleType},
#line 241 "CSSPropertyNames.gperf"
    {"-webkit-line-clamp", CSSPropertyWebkitLineClamp},
#line 284 "CSSPropertyNames.gperf"
    {"-webkit-nbsp-mode", CSSPropertyWebkitNbspMode},
#line 85 "CSSPropertyNames.gperf"
    {"box-sizing", CSSPropertyBoxSizing},
#line 272 "CSSPropertyNames.gperf"
    {"-webkit-mask-position", CSSPropertyWebkitMaskPosition},
#line 273 "CSSPropertyNames.gperf"
    {"-webkit-mask-position-x", CSSPropertyWebkitMaskPositionX},
#line 330 "CSSPropertyNames.gperf"
    {"-webkit-box-sizing", CSSPropertyBoxSizing},
#line 293 "CSSPropertyNames.gperf"
    {"-webkit-rtl-ordering", CSSPropertyWebkitRtlOrdering},
#line 93 "CSSPropertyNames.gperf"
    {"empty-cells", CSSPropertyEmptyCells},
#line 277 "CSSPropertyNames.gperf"
    {"-webkit-mask-repeat-y", CSSPropertyWebkitMaskRepeatY},
#line 179 "CSSPropertyNames.gperf"
    {"-webkit-animation-name", CSSPropertyWebkitAnimationName},
#line 97 "CSSPropertyNames.gperf"
    {"left", CSSPropertyLeft},
#line 94 "CSSPropertyNames.gperf"
    {"float", CSSPropertyFloat},
#line 211 "CSSPropertyNames.gperf"
    {"-webkit-box-flex", CSSPropertyWebkitBoxFlex},
#line 31 "CSSPropertyNames.gperf"
    {"text-rendering", CSSPropertyTextRendering},
#line 217 "CSSPropertyNames.gperf"
    {"-webkit-box-reflect", CSSPropertyWebkitBoxReflect},
#line 202 "CSSPropertyNames.gperf"
    {"-webkit-border-image", CSSPropertyWebkitBorderImage},
#line 65 "CSSPropertyNames.gperf"
    {"border-left", CSSPropertyBorderLeft},
#line 300 "CSSPropertyNames.gperf"
    {"-webkit-text-fill-color", CSSPropertyWebkitTextFillColor},
#line 269 "CSSPropertyNames.gperf"
    {"-webkit-mask-composite", CSSPropertyWebkitMaskComposite},
#line 200 "CSSPropertyNames.gperf"
    {"-webkit-border-fit", CSSPropertyWebkitBorderFit},
#line 182 "CSSPropertyNames.gperf"
    {"-webkit-appearance", CSSPropertyWebkitAppearance},
#line 192 "CSSPropertyNames.gperf"
    {"-webkit-border-before", CSSPropertyWebkitBorderBefore},
#line 103 "CSSPropertyNames.gperf"
    {"margin", CSSPropertyMargin},
#line 25 "CSSPropertyNames.gperf"
    {"font", CSSPropertyFont},
#line 62 "CSSPropertyNames.gperf"
    {"border-image-slice", CSSPropertyBorderImageSlice},
#line 188 "CSSPropertyNames.gperf"
    {"-webkit-border-after", CSSPropertyWebkitBorderAfter},
#line 127 "CSSPropertyNames.gperf"
    {"page", CSSPropertyPage},
#line 274 "CSSPropertyNames.gperf"
    {"-webkit-mask-position-y", CSSPropertyWebkitMaskPositionY},
#line 66 "CSSPropertyNames.gperf"
    {"border-left-color", CSSPropertyBorderLeftColor},
#line 193 "CSSPropertyNames.gperf"
    {"-webkit-border-before-color", CSSPropertyWebkitBorderBeforeColor},
#line 271 "CSSPropertyNames.gperf"
    {"-webkit-mask-origin", CSSPropertyWebkitMaskOrigin},
#line 189 "CSSPropertyNames.gperf"
    {"-webkit-border-after-color", CSSPropertyWebkitBorderAfterColor},
#line 35 "CSSPropertyNames.gperf"
    {"-webkit-writing-mode", CSSPropertyWebkitWritingMode},
#line 253 "CSSPropertyNames.gperf"
    {"-webkit-margin-start", CSSPropertyWebkitMarginStart},
#line 27 "CSSPropertyNames.gperf"
    {"font-size", CSSPropertyFontSize},
#line 100 "CSSPropertyNames.gperf"
    {"list-style-image", CSSPropertyListStyleImage},
#line 180 "CSSPropertyNames.gperf"
    {"-webkit-animation-play-state", CSSPropertyWebkitAnimationPlayState},
#line 270 "CSSPropertyNames.gperf"
    {"-webkit-mask-image", CSSPropertyWebkitMaskImage},
#line 262 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image", CSSPropertyWebkitMaskBoxImage},
#line 67 "CSSPropertyNames.gperf"
    {"border-left-style", CSSPropertyBorderLeftStyle},
#line 252 "CSSPropertyNames.gperf"
    {"-webkit-margin-end", CSSPropertyWebkitMarginEnd},
#line 232 "CSSPropertyNames.gperf"
    {"-webkit-font-size-delta", CSSPropertyWebkitFontSizeDelta},
#line 194 "CSSPropertyNames.gperf"
    {"-webkit-border-before-style", CSSPropertyWebkitBorderBeforeStyle},
#line 28 "CSSPropertyNames.gperf"
    {"font-style", CSSPropertyFontStyle},
#line 190 "CSSPropertyNames.gperf"
    {"-webkit-border-after-style", CSSPropertyWebkitBorderAfterStyle},
#line 122 "CSSPropertyNames.gperf"
    {"padding", CSSPropertyPadding},
#line 265 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-slice", CSSPropertyWebkitMaskBoxImageSlice},
#line 149 "CSSPropertyNames.gperf"
    {"text-overline", CSSPropertyTextOverline},
#line 98 "CSSPropertyNames.gperf"
    {"letter-spacing", CSSPropertyLetterSpacing},
#line 130 "CSSPropertyNames.gperf"
    {"page-break-inside", CSSPropertyPageBreakInside},
#line 104 "CSSPropertyNames.gperf"
    {"margin-bottom", CSSPropertyMarginBottom},
#line 170 "CSSPropertyNames.gperf"
    {"word-spacing", CSSPropertyWordSpacing},
#line 74 "CSSPropertyNames.gperf"
    {"border-spacing", CSSPropertyBorderSpacing},
#line 150 "CSSPropertyNames.gperf"
    {"text-overline-color", CSSPropertyTextOverlineColor},
#line 165 "CSSPropertyNames.gperf"
    {"visibility", CSSPropertyVisibility},
#line 288 "CSSPropertyNames.gperf"
    {"-webkit-padding-start", CSSPropertyWebkitPaddingStart},
#line 155 "CSSPropertyNames.gperf"
    {"text-transform", CSSPropertyTextTransform},
#line 133 "CSSPropertyNames.gperf"
    {"quotes", CSSPropertyQuotes},
#line 305 "CSSPropertyNames.gperf"
    {"-webkit-transform", CSSPropertyWebkitTransform},
#line 314 "CSSPropertyNames.gperf"
    {"-webkit-transition-property", CSSPropertyWebkitTransitionProperty},
#line 168 "CSSPropertyNames.gperf"
    {"width", CSSPropertyWidth},
#line 61 "CSSPropertyNames.gperf"
    {"border-image-repeat", CSSPropertyBorderImageRepeat},
#line 84 "CSSPropertyNames.gperf"
    {"box-shadow", CSSPropertyBoxShadow},
#line 92 "CSSPropertyNames.gperf"
    {"cursor", CSSPropertyCursor},
#line 154 "CSSPropertyNames.gperf"
    {"text-shadow", CSSPropertyTextShadow},
#line 218 "CSSPropertyNames.gperf"
    {"-webkit-box-shadow", CSSPropertyWebkitBoxShadow},
#line 287 "CSSPropertyNames.gperf"
    {"-webkit-padding-end", CSSPropertyWebkitPaddingEnd},
#line 107 "CSSPropertyNames.gperf"
    {"margin-top", CSSPropertyMarginTop},
#line 318 "CSSPropertyNames.gperf"
    {"-webkit-user-select", CSSPropertyWebkitUserSelect},
#line 114 "CSSPropertyNames.gperf"
    {"outline", CSSPropertyOutline},
#line 82 "CSSPropertyNames.gperf"
    {"border-width", CSSPropertyBorderWidth},
#line 152 "CSSPropertyNames.gperf"
    {"text-overline-style", CSSPropertyTextOverlineStyle},
#line 304 "CSSPropertyNames.gperf"
    {"-webkit-text-stroke-width", CSSPropertyWebkitTextStrokeWidth},
#line 69 "CSSPropertyNames.gperf"
    {"border-radius", CSSPropertyBorderRadius},
#line 123 "CSSPropertyNames.gperf"
    {"padding-bottom", CSSPropertyPaddingBottom},
#line 115 "CSSPropertyNames.gperf"
    {"outline-color", CSSPropertyOutlineColor},
#line 203 "CSSPropertyNames.gperf"
    {"-webkit-border-radius", CSSPropertyWebkitBorderRadius},
#line 249 "CSSPropertyNames.gperf"
    {"-webkit-margin-collapse", CSSPropertyWebkitMarginCollapse},
#line 139 "CSSPropertyNames.gperf"
    {"table-layout", CSSPropertyTableLayout},
#line 34 "CSSPropertyNames.gperf"
    {"-webkit-text-size-adjust", CSSPropertyWebkitTextSizeAdjust},
#line 151 "CSSPropertyNames.gperf"
    {"text-overline-mode", CSSPropertyTextOverlineMode},
#line 91 "CSSPropertyNames.gperf"
    {"counter-reset", CSSPropertyCounterReset},
#line 207 "CSSPropertyNames.gperf"
    {"-webkit-border-start-width", CSSPropertyWebkitBorderStartWidth},
#line 162 "CSSPropertyNames.gperf"
    {"unicode-bidi", CSSPropertyUnicodeBidi},
#line 310 "CSSPropertyNames.gperf"
    {"-webkit-transform-style", CSSPropertyWebkitTransformStyle},
#line 301 "CSSPropertyNames.gperf"
    {"-webkit-text-security", CSSPropertyWebkitTextSecurity},
#line 254 "CSSPropertyNames.gperf"
    {"-webkit-marquee", CSSPropertyWebkitMarquee},
#line 264 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-repeat", CSSPropertyWebkitMaskBoxImageRepeat},
#line 109 "CSSPropertyNames.gperf"
    {"max-width", CSSPropertyMaxWidth},
#line 199 "CSSPropertyNames.gperf"
    {"-webkit-border-end-width", CSSPropertyWebkitBorderEndWidth},
#line 156 "CSSPropertyNames.gperf"
    {"text-underline", CSSPropertyTextUnderline},
#line 126 "CSSPropertyNames.gperf"
    {"padding-top", CSSPropertyPaddingTop},
#line 117 "CSSPropertyNames.gperf"
    {"outline-style", CSSPropertyOutlineStyle},
#line 157 "CSSPropertyNames.gperf"
    {"text-underline-color", CSSPropertyTextUnderlineColor},
#line 57 "CSSPropertyNames.gperf"
    {"border-bottom-width", CSSPropertyBorderBottomWidth},
#line 177 "CSSPropertyNames.gperf"
    {"-webkit-animation-fill-mode", CSSPropertyWebkitAnimationFillMode},
#line 111 "CSSPropertyNames.gperf"
    {"min-width", CSSPropertyMinWidth},
#line 231 "CSSPropertyNames.gperf"
    {"-webkit-columns", CSSPropertyWebkitColumns},
#line 247 "CSSPropertyNames.gperf"
    {"-webkit-margin-bottom-collapse", CSSPropertyWebkitMarginBottomCollapse},
#line 234 "CSSPropertyNames.gperf"
    {"-webkit-image-loading-border", CSSPropertyWebkitImageLoadingBorder},
#line 131 "CSSPropertyNames.gperf"
    {"pointer-events", CSSPropertyPointerEvents},
#line 166 "CSSPropertyNames.gperf"
    {"white-space", CSSPropertyWhiteSpace},
#line 334 "CSSPropertyNames.gperf"
    {"-epub-word-break", CSSPropertyWordBreak},
#line 259 "CSSPropertyNames.gperf"
    {"-webkit-marquee-style", CSSPropertyWebkitMarqueeStyle},
#line 321 "CSSPropertyNames.gperf"
    {"-webkit-composition-fill-color", CSSPropertyWebkitCompositionFillColor},
#line 255 "CSSPropertyNames.gperf"
    {"-webkit-marquee-direction", CSSPropertyWebkitMarqueeDirection},
#line 159 "CSSPropertyNames.gperf"
    {"text-underline-style", CSSPropertyTextUnderlineStyle},
#line 313 "CSSPropertyNames.gperf"
    {"-webkit-transition-duration", CSSPropertyWebkitTransitionDuration},
#line 81 "CSSPropertyNames.gperf"
    {"border-top-width", CSSPropertyBorderTopWidth},
#line 113 "CSSPropertyNames.gperf"
    {"orphans", CSSPropertyOrphans},
#line 164 "CSSPropertyNames.gperf"
    {"vertical-align", CSSPropertyVerticalAlign},
#line 158 "CSSPropertyNames.gperf"
    {"text-underline-mode", CSSPropertyTextUnderlineMode},
#line 248 "CSSPropertyNames.gperf"
    {"-webkit-margin-top-collapse", CSSPropertyWebkitMarginTopCollapse},
#line 105 "CSSPropertyNames.gperf"
    {"margin-left", CSSPropertyMarginLeft},
#line 222 "CSSPropertyNames.gperf"
    {"-webkit-column-break-inside", CSSPropertyWebkitColumnBreakInside},
#line 251 "CSSPropertyNames.gperf"
    {"-webkit-margin-before", CSSPropertyWebkitMarginBefore},
#line 250 "CSSPropertyNames.gperf"
    {"-webkit-margin-after", CSSPropertyWebkitMarginAfter},
#line 135 "CSSPropertyNames.gperf"
    {"right", CSSPropertyRight},
#line 129 "CSSPropertyNames.gperf"
    {"page-break-before", CSSPropertyPageBreakBefore},
#line 128 "CSSPropertyNames.gperf"
    {"page-break-after", CSSPropertyPageBreakAfter},
#line 289 "CSSPropertyNames.gperf"
    {"-webkit-perspective", CSSPropertyWebkitPerspective},
#line 119 "CSSPropertyNames.gperf"
    {"overflow", CSSPropertyOverflow},
#line 120 "CSSPropertyNames.gperf"
    {"overflow-x", CSSPropertyOverflowX},
#line 324 "CSSPropertyNames.gperf"
    {"-epub-text-orientation", CSSPropertyWebkitTextOrientation},
#line 148 "CSSPropertyNames.gperf"
    {"text-overflow", CSSPropertyTextOverflow},
#line 90 "CSSPropertyNames.gperf"
    {"counter-increment", CSSPropertyCounterIncrement},
#line 261 "CSSPropertyNames.gperf"
    {"-webkit-mask-attachment", CSSPropertyWebkitMaskAttachment},
#line 176 "CSSPropertyNames.gperf"
    {"-webkit-animation-duration", CSSPropertyWebkitAnimationDuration},
#line 70 "CSSPropertyNames.gperf"
    {"border-right", CSSPropertyBorderRight},
#line 296 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis", CSSPropertyWebkitTextEmphasis},
#line 316 "CSSPropertyNames.gperf"
    {"-webkit-user-drag", CSSPropertyWebkitUserDrag},
#line 243 "CSSPropertyNames.gperf"
    {"-webkit-logical-width", CSSPropertyWebkitLogicalWidth},
#line 322 "CSSPropertyNames.gperf"
    {"-webkit-composition-frame-color", CSSPropertyWebkitCompositionFrameColor},
#line 258 "CSSPropertyNames.gperf"
    {"-webkit-marquee-speed", CSSPropertyWebkitMarqueeSpeed},
#line 71 "CSSPropertyNames.gperf"
    {"border-right-color", CSSPropertyBorderRightColor},
#line 297 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis-color", CSSPropertyWebkitTextEmphasisColor},
#line 336 "CSSPropertyNames.gperf"
    {"-epub-text-combine", CSSPropertyWebkitTextCombine},
#line 306 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin", CSSPropertyWebkitTransformOrigin},
#line 307 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin-x", CSSPropertyWebkitTransformOriginX},
#line 38 "CSSPropertyNames.gperf"
    {"background", CSSPropertyBackground},
#line 124 "CSSPropertyNames.gperf"
    {"padding-left", CSSPropertyPaddingLeft},
#line 256 "CSSPropertyNames.gperf"
    {"-webkit-marquee-increment", CSSPropertyWebkitMarqueeIncrement},
#line 178 "CSSPropertyNames.gperf"
    {"-webkit-animation-iteration-count", CSSPropertyWebkitAnimationIterationCount},
#line 286 "CSSPropertyNames.gperf"
    {"-webkit-padding-before", CSSPropertyWebkitPaddingBefore},
#line 121 "CSSPropertyNames.gperf"
    {"overflow-y", CSSPropertyOverflowY},
#line 257 "CSSPropertyNames.gperf"
    {"-webkit-marquee-repetition", CSSPropertyWebkitMarqueeRepetition},
#line 285 "CSSPropertyNames.gperf"
    {"-webkit-padding-after", CSSPropertyWebkitPaddingAfter},
#line 41 "CSSPropertyNames.gperf"
    {"background-color", CSSPropertyBackgroundColor},
#line 309 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin-z", CSSPropertyWebkitTransformOriginZ},
#line 295 "CSSPropertyNames.gperf"
    {"-webkit-text-decorations-in-effect", CSSPropertyWebkitTextDecorationsInEffect},
#line 50 "CSSPropertyNames.gperf"
    {"background-size", CSSPropertyBackgroundSize},
#line 72 "CSSPropertyNames.gperf"
    {"border-right-style", CSSPropertyBorderRightStyle},
#line 187 "CSSPropertyNames.gperf"
    {"-webkit-background-size", CSSPropertyWebkitBackgroundSize},
#line 29 "CSSPropertyNames.gperf"
    {"font-variant", CSSPropertyFontVariant},
#line 299 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis-style", CSSPropertyWebkitTextEmphasisStyle},
#line 163 "CSSPropertyNames.gperf"
    {"unicode-range", CSSPropertyUnicodeRange},
#line 229 "CSSPropertyNames.gperf"
    {"-webkit-column-span", CSSPropertyWebkitColumnSpan},
#line 183 "CSSPropertyNames.gperf"
    {"-webkit-backface-visibility", CSSPropertyWebkitBackfaceVisibility},
#line 308 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin-y", CSSPropertyWebkitTransformOriginY},
#line 60 "CSSPropertyNames.gperf"
    {"border-image-outset", CSSPropertyBorderImageOutset},
#line 280 "CSSPropertyNames.gperf"
    {"-webkit-max-logical-width", CSSPropertyWebkitMaxLogicalWidth},
#line 64 "CSSPropertyNames.gperf"
    {"border-image-width", CSSPropertyBorderImageWidth},
#line 63 "CSSPropertyNames.gperf"
    {"border-image-source", CSSPropertyBorderImageSource},
#line 26 "CSSPropertyNames.gperf"
    {"font-family", CSSPropertyFontFamily},
#line 331 "CSSPropertyNames.gperf"
    {"-epub-caption-side", CSSPropertyCaptionSide},
#line 68 "CSSPropertyNames.gperf"
    {"border-left-width", CSSPropertyBorderLeftWidth},
#line 195 "CSSPropertyNames.gperf"
    {"-webkit-border-before-width", CSSPropertyWebkitBorderBeforeWidth},
#line 191 "CSSPropertyNames.gperf"
    {"-webkit-border-after-width", CSSPropertyWebkitBorderAfterWidth},
#line 95 "CSSPropertyNames.gperf"
    {"font-stretch", CSSPropertyFontStretch},
#line 246 "CSSPropertyNames.gperf"
    {"-webkit-margin-before-collapse", CSSPropertyWebkitMarginBeforeCollapse},
#line 282 "CSSPropertyNames.gperf"
    {"-webkit-min-logical-width", CSSPropertyWebkitMinLogicalWidth},
#line 245 "CSSPropertyNames.gperf"
    {"-webkit-margin-after-collapse", CSSPropertyWebkitMarginAfterCollapse},
#line 208 "CSSPropertyNames.gperf"
    {"-webkit-border-vertical-spacing", CSSPropertyWebkitBorderVerticalSpacing},
#line 263 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-outset", CSSPropertyWebkitMaskBoxImageOutset},
#line 267 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-width", CSSPropertyWebkitMaskBoxImageWidth},
#line 266 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-source", CSSPropertyWebkitMaskBoxImageSource},
#line 214 "CSSPropertyNames.gperf"
    {"-webkit-box-ordinal-group", CSSPropertyWebkitBoxOrdinalGroup},
#line 47 "CSSPropertyNames.gperf"
    {"background-repeat", CSSPropertyBackgroundRepeat},
#line 48 "CSSPropertyNames.gperf"
    {"background-repeat-x", CSSPropertyBackgroundRepeatX},
#line 40 "CSSPropertyNames.gperf"
    {"background-clip", CSSPropertyBackgroundClip},
#line 184 "CSSPropertyNames.gperf"
    {"-webkit-background-clip", CSSPropertyWebkitBackgroundClip},
#line 153 "CSSPropertyNames.gperf"
    {"text-overline-width", CSSPropertyTextOverlineWidth},
#line 298 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis-position", CSSPropertyWebkitTextEmphasisPosition},
#line 54 "CSSPropertyNames.gperf"
    {"border-bottom-left-radius", CSSPropertyBorderBottomLeftRadius},
#line 221 "CSSPropertyNames.gperf"
    {"-webkit-column-break-before", CSSPropertyWebkitColumnBreakBefore},
#line 326 "CSSPropertyNames.gperf"
    {"-webkit-border-bottom-left-radius", CSSPropertyBorderBottomLeftRadius},
#line 220 "CSSPropertyNames.gperf"
    {"-webkit-column-break-after", CSSPropertyWebkitColumnBreakAfter},
#line 44 "CSSPropertyNames.gperf"
    {"background-position", CSSPropertyBackgroundPosition},
#line 45 "CSSPropertyNames.gperf"
    {"background-position-x", CSSPropertyBackgroundPositionX},
#line 317 "CSSPropertyNames.gperf"
    {"-webkit-user-modify", CSSPropertyWebkitUserModify},
#line 49 "CSSPropertyNames.gperf"
    {"background-repeat-y", CSSPropertyBackgroundRepeatY},
#line 224 "CSSPropertyNames.gperf"
    {"-webkit-column-gap", CSSPropertyWebkitColumnGap},
#line 290 "CSSPropertyNames.gperf"
    {"-webkit-perspective-origin", CSSPropertyWebkitPerspectiveOrigin},
#line 291 "CSSPropertyNames.gperf"
    {"-webkit-perspective-origin-x", CSSPropertyWebkitPerspectiveOriginX},
#line 325 "CSSPropertyNames.gperf"
    {"-epub-writing-mode", CSSPropertyWebkitWritingMode},
#line 78 "CSSPropertyNames.gperf"
    {"border-top-left-radius", CSSPropertyBorderTopLeftRadius},
#line 118 "CSSPropertyNames.gperf"
    {"outline-width", CSSPropertyOutlineWidth},
#line 328 "CSSPropertyNames.gperf"
    {"-webkit-border-top-left-radius", CSSPropertyBorderTopLeftRadius},
#line 201 "CSSPropertyNames.gperf"
    {"-webkit-border-horizontal-spacing", CSSPropertyWebkitBorderHorizontalSpacing},
#line 323 "CSSPropertyNames.gperf"
    {"-webkit-overflow-scrolling", CSSPropertyWebkitOverflowScrolling},
#line 185 "CSSPropertyNames.gperf"
    {"-webkit-background-composite", CSSPropertyWebkitBackgroundComposite},
#line 46 "CSSPropertyNames.gperf"
    {"background-position-y", CSSPropertyBackgroundPositionY},
#line 43 "CSSPropertyNames.gperf"
    {"background-origin", CSSPropertyBackgroundOrigin},
#line 292 "CSSPropertyNames.gperf"
    {"-webkit-perspective-origin-y", CSSPropertyWebkitPerspectiveOriginY},
#line 186 "CSSPropertyNames.gperf"
    {"-webkit-background-origin", CSSPropertyWebkitBackgroundOrigin},
#line 30 "CSSPropertyNames.gperf"
    {"font-weight", CSSPropertyFontWeight},
#line 106 "CSSPropertyNames.gperf"
    {"margin-right", CSSPropertyMarginRight},
#line 160 "CSSPropertyNames.gperf"
    {"text-underline-width", CSSPropertyTextUnderlineWidth},
#line 42 "CSSPropertyNames.gperf"
    {"background-image", CSSPropertyBackgroundImage},
#line 225 "CSSPropertyNames.gperf"
    {"-webkit-column-rule", CSSPropertyWebkitColumnRule},
#line 333 "CSSPropertyNames.gperf"
    {"-epub-text-transform", CSSPropertyTextTransform},
#line 230 "CSSPropertyNames.gperf"
    {"-webkit-column-width", CSSPropertyWebkitColumnWidth},
#line 226 "CSSPropertyNames.gperf"
    {"-webkit-column-rule-color", CSSPropertyWebkitColumnRuleColor},
#line 223 "CSSPropertyNames.gperf"
    {"-webkit-column-count", CSSPropertyWebkitColumnCount},
#line 125 "CSSPropertyNames.gperf"
    {"padding-right", CSSPropertyPaddingRight},
#line 96 "CSSPropertyNames.gperf"
    {"height", CSSPropertyHeight},
#line 227 "CSSPropertyNames.gperf"
    {"-webkit-column-rule-style", CSSPropertyWebkitColumnRuleStyle},
#line 116 "CSSPropertyNames.gperf"
    {"outline-offset", CSSPropertyOutlineOffset},
#line 212 "CSSPropertyNames.gperf"
    {"-webkit-box-flex-group", CSSPropertyWebkitBoxFlexGroup},
#line 238 "CSSPropertyNames.gperf"
    {"-webkit-hyphens", CSSPropertyWebkitHyphens},
#line 32 "CSSPropertyNames.gperf"
    {"-webkit-font-smoothing", CSSPropertyWebkitFontSmoothing},
#line 37 "CSSPropertyNames.gperf"
    {"line-height", CSSPropertyLineHeight},
#line 73 "CSSPropertyNames.gperf"
    {"border-right-width", CSSPropertyBorderRightWidth},
#line 279 "CSSPropertyNames.gperf"
    {"-webkit-match-nearest-mail-blockquote-color", CSSPropertyWebkitMatchNearestMailBlockquoteColor},
#line 108 "CSSPropertyNames.gperf"
    {"max-height", CSSPropertyMaxHeight},
#line 110 "CSSPropertyNames.gperf"
    {"min-height", CSSPropertyMinHeight},
#line 55 "CSSPropertyNames.gperf"
    {"border-bottom-right-radius", CSSPropertyBorderBottomRightRadius},
#line 327 "CSSPropertyNames.gperf"
    {"-webkit-border-bottom-right-radius", CSSPropertyBorderBottomRightRadius},
#line 337 "CSSPropertyNames.gperf"
    {"-epub-text-emphasis", CSSPropertyWebkitTextEmphasis},
#line 338 "CSSPropertyNames.gperf"
    {"-epub-text-emphasis-color", CSSPropertyWebkitTextEmphasisColor},
#line 315 "CSSPropertyNames.gperf"
    {"-webkit-transition-timing-function", CSSPropertyWebkitTransitionTimingFunction},
#line 79 "CSSPropertyNames.gperf"
    {"border-top-right-radius", CSSPropertyBorderTopRightRadius},
#line 39 "CSSPropertyNames.gperf"
    {"background-attachment", CSSPropertyBackgroundAttachment},
#line 329 "CSSPropertyNames.gperf"
    {"-webkit-border-top-right-radius", CSSPropertyBorderTopRightRadius},
#line 339 "CSSPropertyNames.gperf"
    {"-epub-text-emphasis-style", CSSPropertyWebkitTextEmphasisStyle},
#line 244 "CSSPropertyNames.gperf"
    {"-webkit-logical-height", CSSPropertyWebkitLogicalHeight},
#line 181 "CSSPropertyNames.gperf"
    {"-webkit-animation-timing-function", CSSPropertyWebkitAnimationTimingFunction},
#line 319 "CSSPropertyNames.gperf"
    {"-webkit-touch-callout", CSSPropertyWebkitTouchCallout},
#line 281 "CSSPropertyNames.gperf"
    {"-webkit-max-logical-height", CSSPropertyWebkitMaxLogicalHeight},
#line 283 "CSSPropertyNames.gperf"
    {"-webkit-min-logical-height", CSSPropertyWebkitMinLogicalHeight},
#line 228 "CSSPropertyNames.gperf"
    {"-webkit-column-rule-width", CSSPropertyWebkitColumnRuleWidth},
#line 237 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-limit-before", CSSPropertyWebkitHyphenateLimitBefore},
#line 236 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-limit-after", CSSPropertyWebkitHyphenateLimitAfter},
#line 143 "CSSPropertyNames.gperf"
    {"text-line-through", CSSPropertyTextLineThrough},
#line 235 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-character", CSSPropertyWebkitHyphenateCharacter},
#line 144 "CSSPropertyNames.gperf"
    {"text-line-through-color", CSSPropertyTextLineThroughColor},
#line 146 "CSSPropertyNames.gperf"
    {"text-line-through-style", CSSPropertyTextLineThroughStyle},
#line 145 "CSSPropertyNames.gperf"
    {"text-line-through-mode", CSSPropertyTextLineThroughMode},
#line 335 "CSSPropertyNames.gperf"
    {"-epub-hyphens", CSSPropertyWebkitHyphens},
#line 233 "CSSPropertyNames.gperf"
    {"-webkit-highlight", CSSPropertyWebkitHighlight},
#line 320 "CSSPropertyNames.gperf"
    {"-webkit-tap-highlight-color", CSSPropertyWebkitTapHighlightColor},
#line 147 "CSSPropertyNames.gperf"
    {"text-line-through-width", CSSPropertyTextLineThroughWidth}
  };

static const short lookup[] =
  {
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      0,  -1,  -1,  -1,  -1,   1,  -1,  -1,  -1,  -1,
      2,  -1,  -1,  -1,  -1,   3,  -1,  -1,  -1,  -1,
      4,  -1,  -1,  -1,  -1,   5,   6,  -1,  -1,  -1,
      7,  -1,  -1,  -1,  -1,   8,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      9,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     10,  -1,  -1,  -1,  -1,  -1,  11,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  12,  -1,  -1,  -1,  -1,
     -1,  13,  -1,  -1,  -1,  14,  15,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  16,  -1,  -1,  -1,  -1,
     17,  -1,  -1,  -1,  -1,  -1,  18,  -1,  -1,  -1,
     -1,  19,  -1,  -1,  -1,  -1,  20,  -1,  -1,  -1,
     21,  22,  -1,  -1,  -1,  23,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     24,  -1,  -1,  -1,  -1,  -1,  25,  -1,  -1,  -1,
     26,  -1,  -1,  -1,  -1,  27,  -1,  -1,  -1,  -1,
     28,  29,  -1,  -1,  -1,  30,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  31,  -1,  -1,  -1,
     32,  -1,  -1,  -1,  -1,  33,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  34,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     35,  -1,  -1,  -1,  -1,  36,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  37,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  38,  -1,  -1,  -1,  39,  -1,  -1,  -1,  -1,
     40,  41,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  42,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  43,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  44,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  45,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     46,  -1,  -1,  -1,  -1,  47,  48,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  49,  -1,  -1,  -1,  -1,
     -1,  50,  -1,  -1,  -1,  51,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  52,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  53,  -1,  -1,  -1,
     54,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  55,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  56,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  57,  58,  -1,  -1,  -1,
     59,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  60,  -1,  -1,  -1,
     61,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  62,  -1,  -1,  -1,  -1,  63,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  64,  -1,  -1,  -1,
     -1,  -1,  65,  -1,  -1,  66,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  67,  68,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  69,  70,  -1,  -1,  -1,
     -1,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     72,  73,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  74,  -1,  -1,  -1,  75,  76,  -1,  -1,  -1,
     -1,  77,  -1,  -1,  -1,  -1,  -1,  -1,  78,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  79,  -1,  -1,  -1,  -1,  -1,  80,  -1,  -1,
     81,  -1,  -1,  -1,  -1,  -1,  82,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  83,  -1,  -1,
     84,  85,  -1,  -1,  -1,  86,  87,  -1,  -1,  -1,
     88,  89,  -1,  -1,  -1,  90,  91,  -1,  -1,  -1,
     92,  93,  -1,  -1,  -1,  -1,  94,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  95,  -1,  -1,  -1,
     96,  -1,  -1,  -1,  -1,  -1,  97,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  98,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  99,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 100,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 101,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 102,  -1,  -1,  -1, 103, 104,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 105,  -1,  -1, 106, 107,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 108,  -1,  -1,  -1,  -1, 109,  -1,  -1,
     -1,  -1, 110,  -1,  -1, 111, 112,  -1,  -1,  -1,
     -1, 113,  -1,  -1,  -1, 114,  -1,  -1,  -1,  -1,
    115,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    116,  -1,  -1,  -1,  -1, 117,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 118,  -1,  -1,  -1,  -1,
     -1, 119,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 120,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    121,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 122,  -1,  -1,
    123, 124,  -1,  -1,  -1,  -1, 125,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 126,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    127, 128,  -1,  -1,  -1, 129,  -1,  -1,  -1,  -1,
     -1, 130,  -1,  -1,  -1,  -1, 131,  -1,  -1,  -1,
    132,  -1,  -1,  -1,  -1, 133,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 134,  -1,  -1,  -1,  -1,
    135,  -1,  -1,  -1,  -1, 136,  -1, 137,  -1,  -1,
     -1, 138,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    139,  -1,  -1,  -1,  -1, 140,  -1,  -1,  -1,  -1,
    141,  -1,  -1,  -1,  -1, 142,  -1,  -1,  -1,  -1,
    143, 144,  -1,  -1,  -1,  -1, 145,  -1,  -1,  -1,
     -1, 146,  -1,  -1,  -1, 147,  -1,  -1,  -1,  -1,
    148,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    149,  -1,  -1,  -1,  -1,  -1,  -1, 150,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 151,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    152, 153,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 154,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    155, 156,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    157,  -1,  -1,  -1,  -1,  -1, 158,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 159,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 160,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 161,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    162,  -1,  -1,  -1,  -1, 163,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    164,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    165,  -1,  -1,  -1,  -1, 166,  -1,  -1,  -1,  -1,
    167,  -1,  -1,  -1,  -1, 168,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 169,  -1,  -1,  -1,
     -1, 170,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    171,  -1,  -1,  -1,  -1,  -1,  -1, 172,  -1,  -1,
    173,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    174,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    175,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    176, 177,  -1,  -1,  -1, 178, 179,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 180, 181,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 182,  -1,  -1,  -1,
    183, 184,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 185,  -1,  -1,  -1, 186,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 187, 188,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 189, 190,  -1,  -1,
    191,  -1,  -1,  -1,  -1, 192,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 193,  -1,  -1,  -1,  -1,
    194,  -1,  -1,  -1,  -1,  -1, 195,  -1,  -1,  -1,
    196,  -1,  -1,  -1,  -1, 197, 198,  -1,  -1,  -1,
    199,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    200,  -1,  -1,  -1,  -1,  -1, 201,  -1,  -1,  -1,
     -1, 202,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 203, 204,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    205, 206,  -1,  -1,  -1, 207,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    208, 209, 210,  -1,  -1, 211,  -1,  -1,  -1,  -1,
     -1, 212,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    213, 214,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 215,  -1,
     -1,  -1,  -1,  -1,  -1, 216,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 217,  -1,  -1,  -1,
    218, 219, 220,  -1,  -1, 221,  -1,  -1,  -1,  -1,
    222,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 223,  -1,  -1,  -1,  -1, 224,  -1,  -1,
    225,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 226,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    227,  -1,  -1,  -1,  -1, 228,  -1,  -1, 229,  -1,
     -1,  -1,  -1,  -1,  -1, 230,  -1,  -1,  -1,  -1,
     -1, 231,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 232,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 233,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 234,  -1,  -1,  -1,
     -1, 235,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    236, 237,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    238,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 239,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 240,  -1,  -1,  -1,  -1, 241,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 242,  -1,  -1,  -1, 243, 244,  -1,  -1,  -1,
    245,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 246,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 247,  -1,  -1,  -1,
     -1, 248,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 249,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 250,  -1,  -1,  -1,
     -1, 251,  -1,  -1,  -1,  -1, 252,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 253, 254,  -1,  -1,  -1,
     -1,  -1, 255,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 256,  -1,  -1,  -1, 257,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 258, 259,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 260,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 261,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 262, 263,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 264, 265,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 266,  -1,  -1,  -1,  -1,
     -1, 267,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    268,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 269,  -1,  -1,  -1, 270,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 271,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    272,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 273,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 274,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    275,  -1, 276,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    277,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    278,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 279,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 280,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 281, 282, 283,  -1,  -1,
     -1,  -1,  -1, 284,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 285,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 286,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 287,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 288,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    289,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 290,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    291,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    292,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 293,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 294,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 295,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 296,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 297,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 298,  -1,  -1,  -1,  -1,
    299,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 300,  -1,  -1, 301,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 302,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    303,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 304,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    305,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 306,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 307,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 308,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 309,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 310,  -1,  -1,  -1,
     -1, 311,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 312,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 313,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 314,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 315,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 316,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 317
  };

const struct Property *
CSSPropertyNamesHash::findPropertyImpl (register const char *str, register unsigned int len)
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = propery_hash_function (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = property_wordlist[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &property_wordlist[index];
            }
        }
    }
  return 0;
}
#line 340 "CSSPropertyNames.gperf"

const Property* findProperty(register const char* str, register unsigned int len)
{
    return CSSPropertyNamesHash::findPropertyImpl(str, len);
}

const char* getPropertyName(CSSPropertyID id)
{
    if (id < firstCSSProperty)
        return 0;
    int index = id - firstCSSProperty;
    if (index >= numCSSProperties)
        return 0;
    return propertyNameStrings[index];
}

} // namespace WebCore
