/*
 * This file is part of the WebKit open source project.
 * This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

#import "config.h"

#if ENABLE(FILE_SYSTEM)

#import "DOMInternal.h"

#import "DOMEntrySync.h"

#import "DOMBlobInternal.h"
#import "DOMCSSRuleInternal.h"
#import "DOMCSSValueInternal.h"
#import "DOMDOMFileSystemSyncInternal.h"
#import "DOMDirectoryEntrySyncInternal.h"
#import "DOMEntrySyncInternal.h"
#import "DOMEventInternal.h"
#import "DOMFileSystemSync.h"
#import "DOMMetadataInternal.h"
#import "DOMNodeInternal.h"
#import "DOMStyleSheetInternal.h"
#import "DirectoryEntrySync.h"
#import "EntrySync.h"
#import "ExceptionHandlers.h"
#import "JSMainThreadExecState.h"
#import "KURL.h"
#import "Metadata.h"
#import "ThreadCheck.h"
#import "WebCoreObjCExtras.h"
#import "WebScriptObjectPrivate.h"
#import <wtf/GetPtr.h>

#define IMPL reinterpret_cast<WebCore::EntrySync*>(_internal)

@implementation DOMEntrySync

- (void)dealloc
{
    if (WebCoreObjCScheduleDeallocateOnMainThread([DOMEntrySync class], self))
        return;

    if (_internal)
        IMPL->deref();
    [super dealloc];
}

- (void)finalize
{
    if (_internal)
        IMPL->deref();
    [super finalize];
}

- (BOOL)isFile
{
    WebCore::JSMainThreadNullState state;
    return IMPL->isFile();
}

- (BOOL)isDirectory
{
    WebCore::JSMainThreadNullState state;
    return IMPL->isDirectory();
}

- (NSString *)name
{
    WebCore::JSMainThreadNullState state;
    return IMPL->name();
}

- (NSString *)fullPath
{
    WebCore::JSMainThreadNullState state;
    return IMPL->fullPath();
}

- (DOMDOMFileSystemSync *)filesystem
{
    WebCore::JSMainThreadNullState state;
    return kit(WTF::getPtr(IMPL->filesystem()));
}

- (DOMMetadata *)getMetadata
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    DOMMetadata *result = kit(WTF::getPtr(IMPL->getMetadata(ec)));
    WebCore::raiseOnDOMError(ec);
    return result;
}

- (DOMEntrySync *)moveTo:(DOMDirectoryEntrySync *)parent name:(NSString *)inName
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    DOMEntrySync *result = kit(WTF::getPtr(IMPL->moveTo(core(parent), inName, ec)));
    WebCore::raiseOnDOMError(ec);
    return result;
}

- (DOMEntrySync *)copyTo:(DOMDirectoryEntrySync *)parent name:(NSString *)inName
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    DOMEntrySync *result = kit(WTF::getPtr(IMPL->copyTo(core(parent), inName, ec)));
    WebCore::raiseOnDOMError(ec);
    return result;
}

- (NSString *)toURL
{
    WebCore::JSMainThreadNullState state;
    return IMPL->toURL();
}

- (void)remove
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    IMPL->remove(ec);
    WebCore::raiseOnDOMError(ec);
}

- (DOMDirectoryEntrySync *)getParent
{
    WebCore::JSMainThreadNullState state;
    return kit(WTF::getPtr(IMPL->getParent()));
}

@end

WebCore::EntrySync* core(DOMEntrySync *wrapper)
{
    return wrapper ? reinterpret_cast<WebCore::EntrySync*>(wrapper->_internal) : 0;
}

DOMEntrySync *kit(WebCore::EntrySync* value)
{
    { DOM_ASSERT_MAIN_THREAD(); WebCoreThreadViolationCheckRoundOne(); };
    if (!value)
        return nil;
    if (DOMEntrySync *wrapper = getDOMWrapper(value))
        return [[wrapper retain] autorelease];
    DOMEntrySync *wrapper = [[DOMEntrySync alloc] _init];
    wrapper->_internal = reinterpret_cast<DOMObjectInternal*>(value);
    value->ref();
    addDOMWrapper(wrapper, value);
    return [wrapper autorelease];
}

#endif // ENABLE(FILE_SYSTEM)
