/*
 * This file is part of the WebKit open source project.
 * This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

#import "config.h"

#if ENABLE(FILE_SYSTEM)

#import "DOMInternal.h"

#import "DOMFileWriter.h"

#import "Blob.h"
#import "DOMBlobInternal.h"
#import "DOMCSSRuleInternal.h"
#import "DOMCSSValueInternal.h"
#import "DOMEventInternal.h"
#import "DOMFileErrorInternal.h"
#import "DOMFileWriterInternal.h"
#import "DOMNodeInternal.h"
#import "DOMStyleSheetInternal.h"
#import "EventListener.h"
#import "ExceptionHandlers.h"
#import "FileError.h"
#import "FileWriter.h"
#import "JSMainThreadExecState.h"
#import "ObjCEventListener.h"
#import "ThreadCheck.h"
#import "WebCoreObjCExtras.h"
#import "WebScriptObjectPrivate.h"
#import <wtf/GetPtr.h>

#define IMPL reinterpret_cast<WebCore::FileWriter*>(_internal)

@implementation DOMFileWriter

- (void)dealloc
{
    if (WebCoreObjCScheduleDeallocateOnMainThread([DOMFileWriter class], self))
        return;

    if (_internal)
        IMPL->deref();
    [super dealloc];
}

- (void)finalize
{
    if (_internal)
        IMPL->deref();
    [super finalize];
}

- (unsigned short)readyState
{
    WebCore::JSMainThreadNullState state;
    return IMPL->readyState();
}

- (DOMFileError *)error
{
    WebCore::JSMainThreadNullState state;
    return kit(WTF::getPtr(IMPL->error()));
}

- (long long)position
{
    WebCore::JSMainThreadNullState state;
    return IMPL->position();
}

- (long long)length
{
    WebCore::JSMainThreadNullState state;
    return IMPL->length();
}

- (id <DOMEventListener>)onwritestart
{
    WebCore::JSMainThreadNullState state;
    return kit(IMPL->onwritestart());
}

- (void)setOnwritestart:(id <DOMEventListener>)newOnwritestart
{
    WebCore::JSMainThreadNullState state;
    ASSERT(newOnwritestart);

    IMPL->setOnwritestart(WTF::getPtr(nativeEventListener));
}

- (id <DOMEventListener>)onprogress
{
    WebCore::JSMainThreadNullState state;
    return kit(IMPL->onprogress());
}

- (void)setOnprogress:(id <DOMEventListener>)newOnprogress
{
    WebCore::JSMainThreadNullState state;
    ASSERT(newOnprogress);

    IMPL->setOnprogress(WTF::getPtr(nativeEventListener));
}

- (id <DOMEventListener>)onwrite
{
    WebCore::JSMainThreadNullState state;
    return kit(IMPL->onwrite());
}

- (void)setOnwrite:(id <DOMEventListener>)newOnwrite
{
    WebCore::JSMainThreadNullState state;
    ASSERT(newOnwrite);

    IMPL->setOnwrite(WTF::getPtr(nativeEventListener));
}

- (id <DOMEventListener>)onabort
{
    WebCore::JSMainThreadNullState state;
    return kit(IMPL->onabort());
}

- (void)setOnabort:(id <DOMEventListener>)newOnabort
{
    WebCore::JSMainThreadNullState state;
    ASSERT(newOnabort);

    IMPL->setOnabort(WTF::getPtr(nativeEventListener));
}

- (id <DOMEventListener>)onerror
{
    WebCore::JSMainThreadNullState state;
    return kit(IMPL->onerror());
}

- (void)setOnerror:(id <DOMEventListener>)newOnerror
{
    WebCore::JSMainThreadNullState state;
    ASSERT(newOnerror);

    IMPL->setOnerror(WTF::getPtr(nativeEventListener));
}

- (id <DOMEventListener>)onwriteend
{
    WebCore::JSMainThreadNullState state;
    return kit(IMPL->onwriteend());
}

- (void)setOnwriteend:(id <DOMEventListener>)newOnwriteend
{
    WebCore::JSMainThreadNullState state;
    ASSERT(newOnwriteend);

    IMPL->setOnwriteend(WTF::getPtr(nativeEventListener));
}

- (void)write:(DOMBlob *)data
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    IMPL->write(core(data), ec);
    WebCore::raiseOnDOMError(ec);
}

- (void)seek:(long long)inPosition
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    IMPL->seek(inPosition, ec);
    WebCore::raiseOnDOMError(ec);
}

- (void)truncate:(long long)size
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    IMPL->truncate(size, ec);
    WebCore::raiseOnDOMError(ec);
}

- (void)abort
{
    WebCore::JSMainThreadNullState state;
    WebCore::ExceptionCode ec = 0;
    IMPL->abort(ec);
    WebCore::raiseOnDOMError(ec);
}

@end

WebCore::FileWriter* core(DOMFileWriter *wrapper)
{
    return wrapper ? reinterpret_cast<WebCore::FileWriter*>(wrapper->_internal) : 0;
}

DOMFileWriter *kit(WebCore::FileWriter* value)
{
    { DOM_ASSERT_MAIN_THREAD(); WebCoreThreadViolationCheckRoundOne(); };
    if (!value)
        return nil;
    if (DOMFileWriter *wrapper = getDOMWrapper(value))
        return [[wrapper retain] autorelease];
    DOMFileWriter *wrapper = [[DOMFileWriter alloc] _init];
    wrapper->_internal = reinterpret_cast<DOMObjectInternal*>(value);
    value->ref();
    addDOMWrapper(wrapper, value);
    return [wrapper autorelease];
}

#endif // ENABLE(FILE_SYSTEM)
