/*
 * This file is part of the WebKit open source project.
 * This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

#import "config.h"

#if ENABLE(WEBGL)

#import "DOMInternal.h"

#import "DOMWebGLContextAttributes.h"

#import "DOMBlobInternal.h"
#import "DOMCSSRuleInternal.h"
#import "DOMCSSValueInternal.h"
#import "DOMEventInternal.h"
#import "DOMNodeInternal.h"
#import "DOMStyleSheetInternal.h"
#import "DOMWebGLContextAttributesInternal.h"
#import "ExceptionHandlers.h"
#import "JSMainThreadExecState.h"
#import "ThreadCheck.h"
#import "WebCoreObjCExtras.h"
#import "WebGLContextAttributes.h"
#import "WebScriptObjectPrivate.h"
#import <wtf/GetPtr.h>

#define IMPL reinterpret_cast<WebCore::WebGLContextAttributes*>(_internal)

@implementation DOMWebGLContextAttributes

- (void)dealloc
{
    if (WebCoreObjCScheduleDeallocateOnMainThread([DOMWebGLContextAttributes class], self))
        return;

    if (_internal)
        IMPL->deref();
    [super dealloc];
}

- (void)finalize
{
    if (_internal)
        IMPL->deref();
    [super finalize];
}

- (BOOL)alpha
{
    WebCore::JSMainThreadNullState state;
    return IMPL->alpha();
}

- (void)setAlpha:(BOOL)newAlpha
{
    WebCore::JSMainThreadNullState state;
    IMPL->setAlpha(newAlpha);
}

- (BOOL)depth
{
    WebCore::JSMainThreadNullState state;
    return IMPL->depth();
}

- (void)setDepth:(BOOL)newDepth
{
    WebCore::JSMainThreadNullState state;
    IMPL->setDepth(newDepth);
}

- (BOOL)stencil
{
    WebCore::JSMainThreadNullState state;
    return IMPL->stencil();
}

- (void)setStencil:(BOOL)newStencil
{
    WebCore::JSMainThreadNullState state;
    IMPL->setStencil(newStencil);
}

- (BOOL)antialias
{
    WebCore::JSMainThreadNullState state;
    return IMPL->antialias();
}

- (void)setAntialias:(BOOL)newAntialias
{
    WebCore::JSMainThreadNullState state;
    IMPL->setAntialias(newAntialias);
}

- (BOOL)premultipliedAlpha
{
    WebCore::JSMainThreadNullState state;
    return IMPL->premultipliedAlpha();
}

- (void)setPremultipliedAlpha:(BOOL)newPremultipliedAlpha
{
    WebCore::JSMainThreadNullState state;
    IMPL->setPremultipliedAlpha(newPremultipliedAlpha);
}

- (BOOL)preserveDrawingBuffer
{
    WebCore::JSMainThreadNullState state;
    return IMPL->preserveDrawingBuffer();
}

- (void)setPreserveDrawingBuffer:(BOOL)newPreserveDrawingBuffer
{
    WebCore::JSMainThreadNullState state;
    IMPL->setPreserveDrawingBuffer(newPreserveDrawingBuffer);
}

@end

WebCore::WebGLContextAttributes* core(DOMWebGLContextAttributes *wrapper)
{
    return wrapper ? reinterpret_cast<WebCore::WebGLContextAttributes*>(wrapper->_internal) : 0;
}

DOMWebGLContextAttributes *kit(WebCore::WebGLContextAttributes* value)
{
    { DOM_ASSERT_MAIN_THREAD(); WebCoreThreadViolationCheckRoundOne(); };
    if (!value)
        return nil;
    if (DOMWebGLContextAttributes *wrapper = getDOMWrapper(value))
        return [[wrapper retain] autorelease];
    DOMWebGLContextAttributes *wrapper = [[DOMWebGLContextAttributes alloc] _init];
    wrapper->_internal = reinterpret_cast<DOMObjectInternal*>(value);
    value->ref();
    addDOMWrapper(wrapper, value);
    return [wrapper autorelease];
}

#endif // ENABLE(WEBGL)
