/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(WEB_AUDIO)

#include "JSOfflineAudioCompletionEvent.h"

#include "AudioBuffer.h"
#include "JSAudioBuffer.h"
#include "OfflineAudioCompletionEvent.h"
#include <wtf/GetPtr.h>

using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSOfflineAudioCompletionEvent);

/* Hash table */
#if ENABLE(JIT)
#define THUNK_GENERATOR(generator) , generator
#else
#define THUNK_GENERATOR(generator)
#endif

static const HashTableValue JSOfflineAudioCompletionEventTableValues[3] =
{
    { "renderedBuffer", DontDelete | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsOfflineAudioCompletionEventRenderedBuffer), (intptr_t)0 THUNK_GENERATOR(0) },
    { "constructor", DontEnum | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsOfflineAudioCompletionEventConstructor), (intptr_t)0 THUNK_GENERATOR(0) },
    { 0, 0, 0, 0 THUNK_GENERATOR(0) }
};

#undef THUNK_GENERATOR
static JSC_CONST_HASHTABLE HashTable JSOfflineAudioCompletionEventTable = { 4, 3, JSOfflineAudioCompletionEventTableValues, 0 };
/* Hash table for constructor */
#if ENABLE(JIT)
#define THUNK_GENERATOR(generator) , generator
#else
#define THUNK_GENERATOR(generator)
#endif

static const HashTableValue JSOfflineAudioCompletionEventConstructorTableValues[1] =
{
    { 0, 0, 0, 0 THUNK_GENERATOR(0) }
};

#undef THUNK_GENERATOR
static JSC_CONST_HASHTABLE HashTable JSOfflineAudioCompletionEventConstructorTable = { 1, 0, JSOfflineAudioCompletionEventConstructorTableValues, 0 };
class JSOfflineAudioCompletionEventConstructor : public DOMConstructorObject {
public:
    JSOfflineAudioCompletionEventConstructor(JSC::ExecState*, JSC::Structure*, JSDOMGlobalObject*);

    virtual bool getOwnPropertySlot(JSC::ExecState*, const JSC::Identifier&, JSC::PropertySlot&);
    virtual bool getOwnPropertyDescriptor(JSC::ExecState*, const JSC::Identifier&, JSC::PropertyDescriptor&);
    static const JSC::ClassInfo s_info;
    static JSC::Structure* createStructure(JSC::JSGlobalData& globalData, JSC::JSValue prototype)
    {
        return JSC::Structure::create(globalData, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), AnonymousSlotCount, &s_info);
    }
protected:
    static const unsigned StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::ImplementsHasInstance | DOMConstructorObject::StructureFlags;
};

const ClassInfo JSOfflineAudioCompletionEventConstructor::s_info = { "OfflineAudioCompletionEventConstructor", &DOMConstructorObject::s_info, &JSOfflineAudioCompletionEventConstructorTable, 0 };

JSOfflineAudioCompletionEventConstructor::JSOfflineAudioCompletionEventConstructor(ExecState* exec, Structure* structure, JSDOMGlobalObject* globalObject)
    : DOMConstructorObject(structure, globalObject)
{
    ASSERT(inherits(&s_info));
    putDirect(exec->globalData(), exec->propertyNames().prototype, JSOfflineAudioCompletionEventPrototype::self(exec, globalObject), DontDelete | ReadOnly);
}

bool JSOfflineAudioCompletionEventConstructor::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSOfflineAudioCompletionEventConstructor, JSDOMWrapper>(exec, &JSOfflineAudioCompletionEventConstructorTable, this, propertyName, slot);
}

bool JSOfflineAudioCompletionEventConstructor::getOwnPropertyDescriptor(ExecState* exec, const Identifier& propertyName, PropertyDescriptor& descriptor)
{
    return getStaticValueDescriptor<JSOfflineAudioCompletionEventConstructor, JSDOMWrapper>(exec, &JSOfflineAudioCompletionEventConstructorTable, this, propertyName, descriptor);
}

/* Hash table for prototype */
#if ENABLE(JIT)
#define THUNK_GENERATOR(generator) , generator
#else
#define THUNK_GENERATOR(generator)
#endif

static const HashTableValue JSOfflineAudioCompletionEventPrototypeTableValues[1] =
{
    { 0, 0, 0, 0 THUNK_GENERATOR(0) }
};

#undef THUNK_GENERATOR
static JSC_CONST_HASHTABLE HashTable JSOfflineAudioCompletionEventPrototypeTable = { 1, 0, JSOfflineAudioCompletionEventPrototypeTableValues, 0 };
const ClassInfo JSOfflineAudioCompletionEventPrototype::s_info = { "OfflineAudioCompletionEventPrototype", &JSC::JSObjectWithGlobalObject::s_info, &JSOfflineAudioCompletionEventPrototypeTable, 0 };

JSObject* JSOfflineAudioCompletionEventPrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSOfflineAudioCompletionEvent>(exec, globalObject);
}

const ClassInfo JSOfflineAudioCompletionEvent::s_info = { "OfflineAudioCompletionEvent", &JSEvent::s_info, &JSOfflineAudioCompletionEventTable, 0 };

JSOfflineAudioCompletionEvent::JSOfflineAudioCompletionEvent(Structure* structure, JSDOMGlobalObject* globalObject, PassRefPtr<OfflineAudioCompletionEvent> impl)
    : JSEvent(structure, globalObject, impl)
{
    ASSERT(inherits(&s_info));
}

JSObject* JSOfflineAudioCompletionEvent::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return new (exec) JSOfflineAudioCompletionEventPrototype(exec->globalData(), globalObject, JSOfflineAudioCompletionEventPrototype::createStructure(exec->globalData(), JSEventPrototype::self(exec, globalObject)));
}

bool JSOfflineAudioCompletionEvent::getOwnPropertySlot(ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    ASSERT_GC_OBJECT_INHERITS(this, &s_info);
    return getStaticValueSlot<JSOfflineAudioCompletionEvent, Base>(exec, &JSOfflineAudioCompletionEventTable, this, propertyName, slot);
}

bool JSOfflineAudioCompletionEvent::getOwnPropertyDescriptor(ExecState* exec, const Identifier& propertyName, PropertyDescriptor& descriptor)
{
    ASSERT_GC_OBJECT_INHERITS(this, &s_info);
    return getStaticValueDescriptor<JSOfflineAudioCompletionEvent, Base>(exec, &JSOfflineAudioCompletionEventTable, this, propertyName, descriptor);
}

JSValue jsOfflineAudioCompletionEventRenderedBuffer(ExecState* exec, JSValue slotBase, const Identifier&)
{
    JSOfflineAudioCompletionEvent* castedThis = static_cast<JSOfflineAudioCompletionEvent*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    OfflineAudioCompletionEvent* imp = static_cast<OfflineAudioCompletionEvent*>(castedThis->impl());
    JSValue result = toJS(exec, castedThis->globalObject(), WTF::getPtr(imp->renderedBuffer()));
    return result;
}


JSValue jsOfflineAudioCompletionEventConstructor(ExecState* exec, JSValue slotBase, const Identifier&)
{
    JSOfflineAudioCompletionEvent* domObject = static_cast<JSOfflineAudioCompletionEvent*>(asObject(slotBase));
    return JSOfflineAudioCompletionEvent::getConstructor(exec, domObject->globalObject());
}

JSValue JSOfflineAudioCompletionEvent::getConstructor(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMConstructor<JSOfflineAudioCompletionEventConstructor>(exec, static_cast<JSDOMGlobalObject*>(globalObject));
}

JSC::JSValue toJS(JSC::ExecState* exec, JSDOMGlobalObject* globalObject, OfflineAudioCompletionEvent* impl)
{
    return wrap<JSOfflineAudioCompletionEvent>(exec, globalObject, impl);
}


}

#endif // ENABLE(WEB_AUDIO)
